# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lab_03/ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(20, 20, 20, 20)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.main_layout.addWidget(self.title_label)
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.main_layout.addWidget(self.btn_gen_keys)
        self.encryption_group = QtWidgets.QLabel(self.centralwidget)
        self.encryption_group.setObjectName("encryption_group")
        self.main_layout.addWidget(self.encryption_group)
        self.plain_label = QtWidgets.QLabel(self.centralwidget)
        self.plain_label.setObjectName("plain_label")
        self.main_layout.addWidget(self.plain_label)
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.main_layout.addWidget(self.txt_plain_text)
        self.encrypt_layout = QtWidgets.QHBoxLayout()
        self.encrypt_layout.setObjectName("encrypt_layout")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.encrypt_layout.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.encrypt_layout.addWidget(self.btn_decrypt)
        self.main_layout.addLayout(self.encrypt_layout)
        self.cipher_label = QtWidgets.QLabel(self.centralwidget)
        self.cipher_label.setObjectName("cipher_label")
        self.main_layout.addWidget(self.cipher_label)
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.main_layout.addWidget(self.txt_cipher_text)
        self.signature_group = QtWidgets.QLabel(self.centralwidget)
        self.signature_group.setObjectName("signature_group")
        self.main_layout.addWidget(self.signature_group)
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setObjectName("info_label")
        self.main_layout.addWidget(self.info_label)
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setMaximumSize(QtCore.QSize(16777215, 80))
        self.txt_info.setObjectName("txt_info")
        self.main_layout.addWidget(self.txt_info)
        self.sign_layout = QtWidgets.QHBoxLayout()
        self.sign_layout.setObjectName("sign_layout")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setObjectName("btn_sign")
        self.sign_layout.addWidget(self.btn_sign)
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setObjectName("btn_verify")
        self.sign_layout.addWidget(self.btn_verify)
        self.main_layout.addLayout(self.sign_layout)
        self.signature_label = QtWidgets.QLabel(self.centralwidget)
        self.signature_label.setObjectName("signature_label")
        self.main_layout.addWidget(self.signature_label)
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setMaximumSize(QtCore.QSize(16777215, 80))
        self.txt_sign.setObjectName("txt_sign")
        self.main_layout.addWidget(self.txt_sign)
        self.footer_label = QtWidgets.QLabel(self.centralwidget)
        self.footer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.footer_label.setObjectName("footer_label")
        self.main_layout.addWidget(self.footer_label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA SIUUUUUU!"))
        MainWindow.setStyleSheet(_translate("MainWindow", "QMainWindow {\n"
"    background-color: #ecf0f1;\n"
"   }"))
        self.title_label.setText(_translate("MainWindow", "RSA Encryption & Digital Signature Tool"))
        self.title_label.setStyleSheet(_translate("MainWindow", "font-size: 18px; font-weight: bold; color: #2c3e50; margin: 10px;"))
        self.btn_gen_keys.setText(_translate("MainWindow", "🔑 Generate RSA Keys"))
        self.btn_gen_keys.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}"))
        self.encryption_group.setText(_translate("MainWindow", "📝 ENCRYPTION / DECRYPTION"))
        self.encryption_group.setStyleSheet(_translate("MainWindow", "font-size: 16px; font-weight: bold; color: #34495e; margin-top: 20px;"))
        self.plain_label.setText(_translate("MainWindow", "Plain Text:"))
        self.plain_label.setStyleSheet(_translate("MainWindow", "font-weight: bold; color: #2c3e50;"))
        self.txt_plain_text.setPlaceholderText(_translate("MainWindow", "Enter your message here..."))
        self.txt_plain_text.setStyleSheet(_translate("MainWindow", "QTextEdit {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"}\n"
"QTextEdit:focus {\n"
"    border-color: #3498db;\n"
"}"))
        self.btn_encrypt.setText(_translate("MainWindow", "🔒 Encrypt"))
        self.btn_encrypt.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #27ae60;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #229954;\n"
"}"))
        self.btn_decrypt.setText(_translate("MainWindow", "🔓 Decrypt"))
        self.btn_decrypt.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #e74c3c;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c0392b;\n"
"}"))
        self.cipher_label.setText(_translate("MainWindow", "Cipher Text (Hex):"))
        self.cipher_label.setStyleSheet(_translate("MainWindow", "font-weight: bold; color: #2c3e50;"))
        self.txt_cipher_text.setPlaceholderText(_translate("MainWindow", "Encrypted data will appear here..."))
        self.txt_cipher_text.setStyleSheet(_translate("MainWindow", "QTextEdit {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"    background-color: #f8f9fa;\n"
"}\n"
"QTextEdit:focus {\n"
"    border-color: #3498db;\n"
"}"))
        self.signature_group.setText(_translate("MainWindow", "✍️ DIGITAL SIGNATURE"))
        self.signature_group.setStyleSheet(_translate("MainWindow", "font-size: 16px; font-weight: bold; color: #34495e; margin-top: 20px;"))
        self.info_label.setText(_translate("MainWindow", "Message to Sign/Verify:"))
        self.info_label.setStyleSheet(_translate("MainWindow", "font-weight: bold; color: #2c3e50;"))
        self.txt_info.setPlaceholderText(_translate("MainWindow", "Enter message to sign or verify..."))
        self.txt_info.setStyleSheet(_translate("MainWindow", "QTextEdit {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"}\n"
"QTextEdit:focus {\n"
"    border-color: #3498db;\n"
"}"))
        self.btn_sign.setText(_translate("MainWindow", "✍️ Sign Message"))
        self.btn_sign.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #9b59b6;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}"))
        self.btn_verify.setText(_translate("MainWindow", "✅ Verify Signature"))
        self.btn_verify.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"    background-color: #f39c12;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"    margin: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e67e22;\n"
"}"))
        self.signature_label.setText(_translate("MainWindow", "Digital Signature (Hex):"))
        self.signature_label.setStyleSheet(_translate("MainWindow", "font-weight: bold; color: #2c3e50;"))
        self.txt_sign.setPlaceholderText(_translate("MainWindow", "Digital signature will appear here..."))
        self.txt_sign.setStyleSheet(_translate("MainWindow", "QTextEdit {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 12px;\n"
"    background-color: #f8f9fa;\n"
"}\n"
"QTextEdit:focus {\n"
"    border-color: #3498db;\n"
"}"))
        self.footer_label.setText(_translate("MainWindow", "💡 Tip: Generate keys first, then you can encrypt/decrypt messages and create digital signatures"))
        self.footer_label.setStyleSheet(_translate("MainWindow", "color: #7f8c8d; font-style: italic; margin-top: 10px;"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
